services:
  
  nginx:
    build: ./nginx
    environment:
      TZ: "America/Chicago"
    ports: 
      - 1338:80
    depends_on:
      - flask_app
      
  flask_app:
    build: ./app
    command: gunicorn --bind 0.0.0.0:4000 wsgi:app
    ports:
      - "4000:4000"
    environment:
      TZ: "America/Chicago"
      DB_URL: "postgresql://postgres:postgres@flask_db:5432/postgres"
    depends_on:
      - flask_db

  flask_db:
    container_name: flask_db
    image: postgres:12
    environment:
      TZ: "America/Chicago"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "postgres"   
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}